### ISSUE TITLE
Inquiry about COVID-19 vaccinations

### ISSUE THREAD

**Issue by Susie0731** [choH/RICE_MCS_FAQ#15]
Me:  I am writing to inquire the COVID-19 vaccinations and related policies at Rice.  I wonder if I can take the COVID-19 vaccinations (CHO cells) in China before arriving at Rice. I know that some Universities in the United States ask the international students to take one of the only three recognized vaccines, namely the Pfizer, Moderna, and Johnson & Johnson vaccines. I am not sure if Rice also asks the international students to take one of these three vaccines?

CMT Vaccine: You will be allowed to take any vaccine available to you in your home country.

**Comment by henryzhongsc** [comment]
Thank you for providing this explicit confirmation. However this inquiry is roughly covered in #8, so I am closing this issue and moving your info to such.
